apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/metrics-server/manifests/overlays/release?ref=v0.7.1 #https://github.com/kubernetes-sigs/metrics-server/releases