apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-core
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: https://github.com/jmhardison/hhouse-apps.git
      revision: HEAD
      directories:
      - path: core/*/overlays/prod
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: core
      source:
        repoURL: https://github.com/jmhardison/hhouse-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'