apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dapr-system

resources:
- namespace.yaml

helmCharts:
- name: dapr
  repo: https://dapr.github.io/helm-charts
  namespace: dapr-system
  valuesFile: values.yaml


