apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-ca-issuer
  namespace: origin-ca-issuer
spec:
  selector:
    matchLabels:
      app: origin-ca-issuer
  replicas: 1
  template:
    metadata:
      labels:
        app: origin-ca-issuer
    spec:
      serviceAccountName: originissuer-control
      containers:
        - name: origin-ca-controller
          image: cloudflare/origin-ca-issuer:v0.9.0
          args:
            - --cluster-resource-namespace=${POD_NAMESPACE}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 200m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 100Mi
      terminationGracePeriodSeconds: 10