apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 1password

resources:
- namespace.yaml

helmCharts:
- name: connect
  includeCRDs: true
  releaseName: connect
  version: 1.15.1
  valuesFile: customvalues.yaml
  repo: https://1password.github.io/connect-helm-charts