apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- namespace.yaml


#get latest versions from https://github.com/kubernetes/kube-state-metrics/releases
images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.9.2

labels:
  - pairs:
      app.kubernetes.io/version: 2.9.2
    includeTemplates: true