---
# Source: kargo/templates/api/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
data:
  KARGO_NAMESPACE: kargo
  LOG_LEVEL: "INFO"
  TLS_ENABLED: "true"
  TLS_CERT_PATH: /etc/kargo/tls.crt
  TLS_KEY_PATH: /etc/kargo/tls.key
  PERMISSIVE_CORS_POLICY_ENABLED: "false"
  ADMIN_ACCOUNT_ENABLED: "true"
  ADMIN_ACCOUNT_TOKEN_ISSUER: https://localhost
  ADMIN_ACCOUNT_TOKEN_AUDIENCE: "localhost"
  ADMIN_ACCOUNT_TOKEN_TTL: "24h"
  ROLLOUTS_INTEGRATION_ENABLED: "true"
---
# Source: kargo/templates/controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-controller
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
data:
  LOG_LEVEL: "INFO"
  GLOBAL_CREDENTIALS_NAMESPACES: ""
  GITCLIENT_NAME: "Kargo Render"
  GITCLIENT_EMAIL: "kargo-render@akuity.io"
  GITCLIENT_SIGNING_KEY_TYPE: "gpg"
  ARGOCD_INTEGRATION_ENABLED: "true"
  ARGOCD_NAMESPACE: argocd
  ARGOCD_WATCH_ARGOCD_NAMESPACE_ONLY: "false"
  ROLLOUTS_INTEGRATION_ENABLED: "true"
  ROLLOUTS_CONTROLLER_INSTANCE_ID: ""
---
# Source: kargo/templates/garbage-collector/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-garbage-collector
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: garbage-collector
data:
  LOG_LEVEL: "INFO"
  NUM_WORKERS: "3"
  MAX_RETAINED_PROMOTIONS: "20"
  MIN_PROMOTION_DELETION_AGE: "336h"
  MAX_RETAINED_FREIGHT: "20"
  MIN_FREIGHT_DELETION_AGE: "336h"
---
# Source: kargo/templates/management-controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-management-controller
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: management-controller
data:
  KARGO_NAMESPACE: kargo
  LOG_LEVEL: "INFO"
---
# Source: kargo/templates/webhooks-server/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-webhooks-server
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhooks-server
data:
  KARGO_NAMESPACE: kargo
  LOG_LEVEL: "INFO"
  CONTROLPLANE_USER_REGEX: ^system:serviceaccount:kargo:(kargo-api|kargo-controller|kargo-garbage-collector|kargo-management-controller)$
---