apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo
resources:
- namespace.yaml
- crd.yaml
- certs.yaml
- configmap.yaml
- cronjobs.yaml
- deployments.yaml
- hooks.yaml
- rolebindings.yaml
- roles.yaml
- sa.yaml
- services.yaml