
# Source: kargo/templates/api/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-api
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-api
---
# Source: kargo/templates/api/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-api-rollouts
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api-rollouts
subjects:
  - kind: ServiceAccount
    namespace: kargo
    name: kargo-api
---
# Source: kargo/templates/controller/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-controller
---
# Source: kargo/templates/controller/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller-argocd
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-argocd
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-controller
---
# Source: kargo/templates/controller/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller-rollouts
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-rollouts
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-controller
---
# Source: kargo/templates/garbage-collector/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-garbage-collector
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: garbage-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-garbage-collector
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-garbage-collector
---
# Source: kargo/templates/management-controller/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-management-controller
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: management-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-management-controller
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-management-controller
---
# Source: kargo/templates/users/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-admin
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-admin
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-admin
---
# Source: kargo/templates/users/cluster-role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-viewer
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-viewer
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-viewer
---
# Source: kargo/templates/webhooks-server/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-webhooks-server
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhooks-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-webhooks-server
subjects:
- kind: ServiceAccount
  namespace: kargo
  name: kargo-webhooks-server
---
# Source: kargo/templates/webhooks-server/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-webhooks-server-ns-controller
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhooks-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-webhooks-server-ns-controller
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: namespace-controller
---
# Source: kargo/templates/webhooks-server/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-webhooks-server-generic-gc
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhooks-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-webhooks-server-generic-gc
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: generic-garbage-collector