
# Source: kargo/templates/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/component: api
---
# Source: kargo/templates/webhooks-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kargo-webhooks-server
  namespace: kargo
  labels:
    helm.sh/chart: kargo-0.8.7
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.8.7"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webhooks-server
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/component: webhooks-server