apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cfargotunnel

resources:
  - ../../base
  - cf-configmap.yaml
  - op-secrets/hhouse-cloudflare-json.yaml

#get latest versions from https://github.com/cloudflare/cloudflared/releases
images:
- name: cloudflare/cloudflared
  newTag: 2024.8.2

replicas:
- name: cloudflared
  count: 2
