apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cfargotunnel

resources:
  - base/deployment.yaml
  - base/cf-configmap.yaml
  - base/namespace.yaml
  - op-secrets/hhouse-cloudflare-json.yaml

#get latest version from https://github.com/cloudflare/cloudflared/releases
images:
- name: cloudflare/cloudflared
  newTag: 2023.6.1

replicas:
- name: cloudflared
  count: 3
