apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/native?ref=v0.14.18 # https://github.com/metallb/metallb/releases
  - addresspool.yaml
  #- metallb-ingress-service.yaml #example service using metallb