apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-agents

resources:
- namespace.yaml
- agent.yaml
- customcollect.yaml
- op-secret.yaml
- eventcollect.yaml

helmCharts:
- name: grafana-agent-operator
  repo: https://grafana.github.io/helm-charts
  namespace: grafana-agents
  includeCRDs: true
