apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: couchdb

resources:
  - namespace.yaml
  - op-secret.yaml
  - certificates/ingress-cert.yaml

helmCharts:
- name: couchdb
  repo: https://apache.github.io/couchdb-helm
  releaseName: couchdb
  namespace: couchdb
  version: 4.5.3
  valuesFile: values.yaml