apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kargo

resources:
- ../../base
- op-secrets/argo-secrets.yaml
- op-secrets/hhouse-cloudflare-api-token-secret_secrets.yaml
- certificates/certs.yaml
- certificates/cloudflare-ca-originissuer.yaml

